import { z } from "zod";

export const createRiderSchema = z.object({
    riderId: z.string().min(2),
    riderCnicNumber: z.string().min(13),
    riderImage: z.string().min(2),
    riderCnicFrontImage: z.string().min(2),
    riderCnicBackImage: z.string().min(2),
    riderAddress: z.string().min(2),
    riderLatitude: z.coerce.number(),
    riderLongitude: z.coerce.number(),
    riderDOB: z.string().min(2),
    drivingLicense: z.string().min(2),
    vehicleRegistrationCard: z.string().min(2),
    riderSelfie: z.string().min(2),
    policeCharacterCertificate: z.string().optional(),
    vehicleModel: z.string().min(2),
    vehicleRegistrationNumber: z.string().min(2),
    vehicleNumberPlateImage: z.string().min(2),
    vehicleType: z.string().min(2),
    fuelType: z.string().optional(),
    isOnline: z.string().min(2),
    approvalStatus: z.string().min(2).optional(),
    rejectReason: z.string().optional(),
}); 

export const updateRiderSchema = z.object({
    riderName: z.string().optional(),
    riderImage: z.string().optional(),
    riderAddress: z.string().optional(),
    riderLatitude: z.coerce.number().optional(),
    riderLongitude: z.coerce.number().optional(),
    riderStatus: z.string().min(2).optional(),
    riderDOB: z.string().min(2).optional(),
    drivingLicense: z.string().min(2).optional(),
    vehicleRegistrationCard: z.string().min(2).optional(),
    riderSelfie: z.string().min(2).optional(),
    policeCharacterCertificate: z.string().optional(),
    vehicleModel: z.string().min(2).optional(),
    vehicleRegistrationNumber: z.string().min(2).optional(),
    vehicleNumberPlateImage: z.string().min(2).optional(),
    vehicleType: z.string().min(2).optional(),
    fuelType: z.string().optional(),
    isOnline: z.string().min(2).optional(),
    approvalStatus: z.string().min(2).optional(),
    rejectReason: z.string().optional(),
});
